import Head from "next/head";
import UserLayout from "../components/UserLayout";
import withAuth from "../HOC/withAuth";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout>
        <main></main>
      </UserLayout>
    </div>
  );
};

export default withAuth(Home);
