import Head from "next/head";
import UserLayout from "../components/UserLayout";
import withAuth from "../HOC/withAuth";
import HomeImage from "../public/HomePage.jpg";
import Image from "next/image";
import Link from "next/link";
import { Button, Container, Grid, SvgIcon, Typography } from "@mui/material";
import { Box } from "@mui/system";
import FacebookIcon from "@mui/icons-material/Facebook";
import InstagramIcon from "@mui/icons-material/Instagram";
import TwitterIcon from "@mui/icons-material/Twitter";

const BoxStyle = {
  position: "absolute",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  textAlign: "center",
  color: "whitesmoke",
};

const AboutStyle = {
  backgroundColor: "secondary.main",
  top: "-64px",
  position: "relative",
  color: "white",
  display: "flex",
  flexDirection: "column",
  justifyContent: "start",
  alignItems: "center",
  height: "400px",
};

const ButtonStyle = {
  color: "white",
  borderColor: "white",
  "&:hover.MuiButton-outlined": {
    color: "primary.main",
    backgroundColor: "white",
    borderColor: "white",
    variant: "filled",
  },
};

const Home = () => {
  const linkItems = [
    {
      path: "https://www.facebook.com",
      icon: FacebookIcon,
    },
    {
      path: "https://www.instagram.com",
      icon: InstagramIcon,
    },
    {
      path: "https://www.twitter.com",
      icon: TwitterIcon,
    },
  ];

  return (
    <Box
      sx={{
        backgroundColor: "black",
        zIndex: 1,
        position: "relative",
      }}
    >
      <Head>
        <title>Hour Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout index="index">
        <main
          style={{
            background: "rgba(0,0,0,0.7)",
            height: "640px",
            top: "-64px",
            position: "relative",
            overflowY: "hidden",
          }}
        >
          <div
            style={{
              position: "relative",
              width: "100%",
              top: "-64px",
              zIndex: -9,
            }}
          >
            <Image src={HomeImage} objectFit="cover" layout="responsive" />
          </div>
          <Box sx={BoxStyle}>
            <Container>
              <Typography variant="h3" color="white" fontWeight="bold" mb={1}>
                Welcome to Hour Hotel
              </Typography>
              <Typography variant="subtitle1" mb={1}>
                We offer hotel rooms for you and your family at a best rate.{" "}
              </Typography>
              <Typography variant="h5" fontWeight="bold" mb={2}>
                Find Your Rooms
              </Typography>
              <Button variant="outlined" sx={ButtonStyle} size="large">
                Check Rooms
              </Button>
            </Container>
          </Box>
        </main>
        <Grid container sx={AboutStyle} id="about">
          <Typography
            variant="h5"
            mt={7}
            fontWeight="bold"
            sx={{ textDecoration: "underline", textUnderlineOffset: 10 }}
          >
            About Us
          </Typography>
          <Typography
            variant="body1"
            mt={4}
            sx={{ width: "550px", textAlign: "center" }}
          >
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora,
            nihil! Nihil necessitatibus corporis tempora unde eum reprehenderit
            maiores, nobis placeat dignissimos aperiam eligendi praesentium
            fugit obcaecati doloribus quam? Voluptates omnis esse accusamus
            dolore praesentium. Alias eligendi asperiores, eveniet obcaecati ea
            eaque impedit voluptate sint dolor, et doloribus velit laudantium
            minima?
          </Typography>
        </Grid>
      </UserLayout>
      <Container sx={{ height: 0 }}>
        <footer
          style={{
            position: "relative",
            top: "-64px",
            marginTop: "2.5rem",
            display: "flex",
            justifyContent: "space-between",
            alignContent: "center",
          }}
        >
          <Typography color="whitesmoke">Copyright Ⓒ 2021</Typography>
          <Box
            sx={{
              display: "flex",
              alignContent: "space-between",
              justifyContent: "space-between",
              width: "8rem",
            }}
          >
            {linkItems.map((item, key) => (
              <Box key={key}>
                <Link href={item.path}>
                  <a target="_blank">
                    <SvgIcon component={item.icon} sx={{ color: "white" }} />
                  </a>
                </Link>
              </Box>
            ))}
          </Box>
        </footer>
      </Container>
    </Box>
  );
};

export default withAuth(Home);
