import { Button, Container, Grid, Typography } from "@mui/material";
import { useRouter } from "next/router";
import { SRLWrapper } from "simple-react-lightbox";
import useSWR from "swr";
import api from "../../axios";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import UserLayout from "../../components/UserLayout";
import { Box } from "@mui/system";

const fetcher = (url) => api.get(url).then((res) => res.data);

const SingleRooms = () => {
  const router = useRouter();
  const { pname } = router.query;
  const { data: rooms } = useSWR(`/category/single/${pname}`, fetcher);

  return (
    <main style={{ background: "#F4F4F4", height: "100%", paddingTop: 50 }}>
      <Head>
        <title>{pname}room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout>
        <Container>
          <Box sx={{ display: "flex" }}>
            <Typography
              variant="h4"
              fontWeight="bold"
              sx={{ marginBottom: 4, marginLeft: 1, flexGrow: 1 }}
            >
              {rooms && rooms.name}room
            </Typography>
            <Button variant="contained" sx={{ height: "2.5rem" }}>
              Book Now
            </Button>
          </Box>
        </Container>
        <SRLWrapper>
          <Grid
            container
            gap={8}
            sx={{
              position: "relative",
              display: "flex",
              justifyContent: "center",
              height: 100,
              maxWidth: "inherit",
            }}
          >
            {rooms &&
              rooms.images.map((img) => {
                return (
                  <Grid item key={img} md={3} xs={12}>
                    <Link href={`${process.env.API_URL}/category/${img}`}>
                      <Box
                        sx={{
                          position: "relative",
                          width: "350px",
                          height: "250px",
                          cursor: "pointer",
                          boxShadow:
                            "0px 3px 1px -2px rgb(0 0 0 / 20%), 0px 2px 2px 0px rgb(0 0 0 / 14%), 0px 1px 5px 0px rgb(0 0 0 / 12%)",
                        }}
                      >
                        <Image
                          alt="image"
                          src={`${process.env.API_URL}/category/${img}`}
                          objectFit="cover"
                          layout="fill"
                        />
                      </Box>
                    </Link>
                  </Grid>
                );
              })}
          </Grid>
        </SRLWrapper>
        <Container>
          <Grid container mt={25} pb={5}>
            <Grid item md={6}>
              <Typography maxWidth={450}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla
                est mollitia, dolores cum natus libero deserunt aliquam, rerum
                accusamus autem voluptas velit iusto nostrum ut expedita, quam
                veniam aspernatur tenetur.
              </Typography>
            </Grid>
            <Grid item md={6} textAlign="end">
              <Box>
                <Typography>
                  <span style={{ fontWeight: "bold" }}>Name: </span>
                  {rooms && rooms.name}
                </Typography>
                <Typography>
                  <span style={{ fontWeight: "bold" }}>Max People: </span>
                  {rooms && rooms.maxPeople}
                </Typography>
                <Typography>
                  <span style={{ fontWeight: "bold" }}>Price per hour: </span>
                  {rooms && rooms.price_per_hour}
                </Typography>
              </Box>
            </Grid>
          </Grid>
        </Container>
      </UserLayout>
    </main>
  );
};

export default SingleRooms;
