import {
  Container,
  Grid,
  Card,
  CardHeader,
  CardMedia,
  CardActions,
  Button,
} from "@mui/material";
import UserLayout from "../../components/UserLayout";
import useSWR from "swr";
import api from "../../axios";
import Head from "next/head";
import router from "next/router";

const fetcher = (url) => api.get(url).then((res) => res.data);

const ButtonStyle = {
  color: "white",
  borderColor: "white",
  "&:hover.MuiButton-outlined": {
    color: "primary.main",
    backgroundColor: "white",
    borderColor: "white",
    variant: "filled",
  },
};

const Rooms = () => {
  const { data: category } = useSWR("/category", fetcher);

  return (
    <UserLayout>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ background: "#F4F4F4", paddingTop: 50 }}>
        <Container>
          <Grid container spacing={2}>
            {category?.map((item) => (
              <Grid item md={4} xs={12} key={item.id}>
                <Card
                  elevation={2}
                  sx={{
                    bgcolor: "primary.main",
                    maxWidth: 345,
                    marginBottom: 3,
                    "&.MuiPaper-root:hover": {
                      boxShadow:
                        "0px 6px 6px -3px rgb(0 0 0 / 20%), 0px 10px 14px 1px rgb(0 0 0 / 14%), 0px 4px 18px 3px rgb(0 0 0 / 12%)",
                    },
                  }}
                >
                  <CardMedia
                    component="img"
                    height="194"
                    image={`${process.env.API_URL}/category/${item.images[0]}`}
                    alt="Paella dish"
                  />
                  <CardHeader
                    title={item.name}
                    subheader={`${item.price_per_hour}/hr`}
                    sx={{
                      "& .MuiCardHeader-title": {
                        color: "white",
                      },
                      "& .MuiCardHeader-subheader": {
                        color: "rgba(255, 255, 255, 0.7)",
                      },
                    }}
                  />
                  <CardActions sx={{ margin: "0 0 3px 5px" }}>
                    <Button
                      disableElevation
                      sx={ButtonStyle}
                      variant="outlined"
                      onClick={() => {
                        router.push(`/rooms/${item.name}`);
                      }}
                    >
                      View
                    </Button>
                    <Button
                      disableElevation
                      variant="outlined"
                      sx={ButtonStyle}
                    >
                      Book
                    </Button>
                  </CardActions>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </main>
    </UserLayout>
  );
};

export default Rooms;

// Time Date Experiment

{
  /* <LocalizationProvider dateAdapter={AdapterDateFns}>
          <form onSubmit={(e) => handleSubmit(e)}>
            <DateTimePicker
              label="Date&Time picker"
              value={value}
              disablePast={true}
              minutesStep={60}
              onChange={handleChange}
              renderInput={(params) => <TextField {...params} />}
            />
            <input type="submit" value="submit" />
          </form>
        </LocalizationProvider> */
}
